#!/bin/bash -ex


# only for ubuntu machines

TARGETS=$1
PORTS=$2
COUNT=$3
SPEED=$4

# install python
apt-get update
apt-get install -y python git

# update pip
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py

# install docker
apt-get update
apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
apt-add-repository 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
apt-get update
apt-cache policy docker-engine
apt-get install -y docker-engine

#add user to docker
sudo usermod -aG docker $(whoami)

# clone stress-tool
git clone https://github.com/prazumovsky/prom-stress-tool
cd prom-stress-tool

# parse ports to array
IFS=',' read -a arrports <<<"$PORTS"

docker build . -t stress
for i in `seq 0 $((TARGETS - 1))`;
do
    docker run -p ${arrports[i]}:${arrports[i]} --name target-$i -e PORT=${arrports[i]} -e COUNT=$COUNT -e SPEED=$SPEED -d stress
done
