heat_template_version: ocata

parameters:
  target_count:
    type: number
    default: 1
  speed:
    type: number
    default: 15
  metric_count:
    type: number
    default: 10000
  ports:
    type: comma_delimited_list
  read:
    type: boolean
    default: false
  read_period:
    type: number
    default: 15
  job_name:
    type: string
  prometheus_url:
    type: string

resources:
  machine:
    type: OS::Nova::Server
    properties:
      name: prazumovsky-test
      image: ubuntu-16-04-amd64-cloudimg
      flavor: m1.medium
      key_name: lab-ssh-private-key
      availability_zone: mcp-scale
      networks:
        - network: listomin-deploy
          fixed_ip: 10.10.0.5
        - network: listomin-control
          fixed_ip: 10.11.0.5
      security_groups:
        - default
        - debug_allow_all
      personality:
        /opt/script.sh: { get_file: "https://raw.githubusercontent.com/prazumovsky/prom-stress-tool/master/common-script" }
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            chmod +x /opt/script.sh
            export TARGETS=%TARGETS%
            export PORTS=%PORTS%
            export COUNT=%COUNT%
            export SPEED=%SPEED%
            export READ=%READ%
            export PROMETHEUS=%PROM%
            export READ_PERIOD=%PERIOD%
            export JOB_NAME=%JOB_NAME%
            sudo bash /opt/script.sh
          params:
            "%PORTS%": { get_param: ports }
            "%COUNT%": { get_param: metric_count }
            "%SPEED%": { get_param: speed }
            "%READ%": { get_param: read }
            "%PROMETHEUS%": { get_param: prometheus_url }
            "%READ_PERIOD%": { get_param: read_period }
            "%JOB_NAME%": { get_param: job_name }
